global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql_exporter:9104"]

  - job_name: "app"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:5000"]
